version: 0.0.{build}

configuration: Release

install:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/install-nuget-3-3-0.ps1'))

init:
- ps: Update-AppveyorBuild -Version "0.0.$env:appveyor_build_number+sha.$($env:appveyor_repo_commit.substring(0,7))"

nuget:
  disable_publish_on_pr: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  package_version: '0.0.{build}'
  assembly_version: '0.0.{build}'
  file_version: '0.0.{build}'
  informational_version: '{version}'

matrix:
  fast_finish: true # fail fast!

clone_depth: 3  

pull_requests:
  do_not_increment_build_number: true

before_build:
  nuget restore DotJEM.Json.Visitor\DotJEM.Json.Visitor.sln

build:
  project: DotJEM.Json.Visitor\DotJEM.Json.Visitor.sln
  publish_nuget: true
  publish_nuget_symbols: true

after_build:
  dir

test:
  assemblies:
    - '**\*.test.dll'

deploy:
  provider: NuGet
  api_key:
    secure: KEHWtW02rf5aCAlwchP0Siow5EA24hwtm09uvsR58bMWirJ8uXl1SidBnNCfJ3cw
  skip_symbols: true
  on:
    branch: master 
